# -*- coding: utf-8 -*-
"""STUDENT_PERFOMANCE_ANALYSIS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17MFf4lBAvSL_8VfCLakCbLtAWkfIsTrl
"""

# Importing required libraries
import pandas as pd #pandas: helps you load and manipulate structured data (tables, CSV).
import matplotlib.pyplot as plt #matplotlib.pyplot: lets you draw basic plots, bar charts, pie charts, etc.
import seaborn as sns #seaborn: makes beautiful and easy statistical plots like box plots, heatmaps, etc.

# Load the CSV file
df = pd.read_csv('/content/StudentsPerformance.csv')

# Show top 5 rows
df.head()

# Info about columns and types
df.info()

# Summary statistics
df.describe()

# Check for missing values
df.isnull().sum()

# Average math score by gender
df.groupby("gender")["math score"].mean()

# Scores based on test preparation
df.groupby("test preparation course")[["math score", "reading score", "writing score"]].mean()

# Scores based on parental education
df.groupby("parental level of education")[["math score", "reading score", "writing score"]].mean()

# Average score for test prep
prep_scores = df.groupby("test preparation course")[["math score", "reading score", "writing score"]].mean()
prep_scores.plot(kind="bar", figsize=(8,5), colormap='viridis')
plt.title("Scores Based on Test Preparation")
plt.ylabel("Average Score")
plt.xticks(rotation=0)
plt.show()

# Math scores by gender
sns.boxplot(x="gender", y="math score", data=df)
plt.title("Math Score by Gender")
plt.show()

df.to_csv("cleaned_student_data.csv", index=False)